.TH ROTN 1 "April 2025" "1.0.0" "rotn manual"
.SH NAME
rotn \- Decrypt Caesar cipher with any rotation
.SH SYNOPSIS
.B rotn
\fI<input>\fR \-s \fI<shift>\fR
.SH DESCRIPTION
Decrypts text encrypted with a Caesar cipher using the specified shift.
.SH OPTIONS
.TP
.B \-s
Specify the shift value for decryption.
.TP
.B \-h
Display help information.
.SH EXAMPLES
rotn "Wklv lv d whvw" -s 3
.SH AUTHOR
Mahros AlQabasy Mahros.elqabasy@gmail.com
