name: Build and Release .deb Package

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deb:
    name: Build Debian Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y dpkg-dev debhelper fakeroot

      - name: Prepare Package Structure
        run: |
          mkdir -p pkg/DEBIAN
          mkdir -p pkg/usr/bin
          mkdir -p pkg/usr/share/man/man1
          mkdir -p pkg/usr/share/doc/linux-tools

          # Copy existing control file
          cp debian/control pkg/DEBIAN/control

          # Copy all scripts to /usr/bin/
          cp src/scripts/* pkg/usr/bin/

          # Make scripts executable
          # chmod +x pkg/usr/bin/*.sh

          # Copy man pages
          cp src/man/man1/*.1 pkg/usr/share/man/man1/

          # Compress man pages
          gzip -f pkg/usr/share/man/man1/*.1

          # Copy documentation
          cp src/docs/COMMANDS/*.md pkg/usr/share/doc/linux-tools/

          # Copy postinst script if it exists
          if [ -f debian/postinst ]; then
            cp debian/postinst pkg/DEBIAN/
            chmod 755 pkg/DEBIAN/postinst
          fi

      - name: Build .deb Package
        run: dpkg-deb --build pkg linux-tools.deb

      - name: Upload Debian package artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-tools-deb
          path: linux-tools.deb

  release:
    name: Create GitHub Release
    needs: build-deb
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Debian package artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-tools-deb

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: linux-tools_1.0.0-1_all.deb
          tag_name: v1.0.0
          release_name: "Release v1.0.0"
          body: "🚀 New Debian package release: **v1.0.0**"
          draft: false
          prerelease: false
